### ISSUE TITLE
Set MOAB Version5.0 as default moab

### ISSUE THREAD

**Issue by zxkjack123** [pyne/install_scripts#23]
As of DAGMC version 3.0, MOAB version 5.0 or higher is required. But the version of moab installed here is Version4.9.1.

**Comment by kkiesling** [comment]
As of right now, PyNE cannot be built with DAGMC 3.0 and MOAB 5.0 so it cannot be set as the default install version here. If you would like to use the latest version of DAGMC/MOAB for other things as well as PyNE, you will need to maintain multiple version unfortunately.

**Comment by ljacobson64** [comment]
If you want to build pyne with MOAB, you need to use MOAB 4.9.1.

**Comment by zxkjack123** [comment]
I want to perform R2S calculation using PyNE. What version of DAGMC/MOAB is the best?

**Comment by ljacobson64** [comment]
DAGMC requires MOAB 5.0 or master and Pyne requires MOAB 4.9.1, so if you want to use both DAGMC and Pyne at the same time then you'll need both version of MOAB installed at the same time.

**Comment by makeclean** [comment]
The way I used to handle it was by compiling the MOAB you want to use with DAGMC as static, and then using a dynamically linked version of MOAB for PyNE

**Comment by zxkjack123** [comment]
I got the idea. 
I should compile the MOAB 5.0 as static for DAGMC 3.0. And compile MOAB 4.9.1 dynamically for PyNE.
Can I compile them both as static? I found that the static lib: `libMOAB.so` (4.9.1) is used when I compile the PyNE.

**Comment by ljacobson64** [comment]
My recommendation is that you build MOAB twice, once with version 4.9.1 with something like ``-prefix=/path/to/moab-4.9.1` and once with version with 5.0 with something like ``-prefix=/path/to/moab-5.0`. Then when you build Pyne, use the 4.9.1 directory and when you build DAGMC, use the 5.0 directory. This is what I do myself and it seems to work pretty well.

**Comment by zxkjack123** [comment]
This issue is out of date.
