### ISSUE TITLE
install scripts require superuser privileges

### ISSUE THREAD

**Issue by Mongwell** [pyne/install_scripts#32]
The Ubuntu install scripts need root privileges to install packages with the 'apt' package manager. Running the install script as `sudo ./ubuntu_16.04.sh <dev | stable>` (or any Ubuntu version) as a regular user will install the dependencies and PyNE itself successfully, but because the script itself is run as superuser, the PyNE installation under `/home/USERNAME/.local/lib/python2.7/site-packages` and all other directories created by the script will be owned by root. This means to import PyNE, python must be run as superuser, which does not seem correct. The user should not have to `chown` their installation to fix this.

**Comment by Mongwell** [comment]
I think the most straightforward way to correct this is to only ask for superuser privilege when necessary, i.e. at the `apt-get install` and `make install` commands. Alternatively, the script can be run with superuser privilege and an additional 'user' argument. `su` can be used to switch back and forth between root and the supplied user, or everything that should belong to the installing user can be chowned at the end.

**Comment by gonuke** [comment]
Thanks for pointing this out - I think the reason we haven't noticed it is that we generally test these scripts as `root` in a docker container.

Feel free to PR a change that explicitly invokes `sudo` on those lines.  

In addition, the `make install` line could be done with some other install prefix that is accessible at user level, eg, `$HOME/.local`

**Comment by Mongwell** [comment]
I think the script installs MOAB to `/home/USERNAME/opt/`, which should be accessible at user level as long as the script isn't run as root, because the script creates that subdirectory. 

There is, however, another issue with installing PyNE with MOAB. I believe it's because the develop branch of PyNE uses the PyMOAB module instead of PyTAPS (as was the goal of [this PR](https://github.com/pyne/pyne/pull/1097)), but the script will install PyTAPS and an older release of MOAB that did not have the PyMOAB module. 

After making the changes described in my last comment and running the install script, I got this error when trying to use the mesh module (taken from this [tutorial](http://pyne.io/tutorial/07.html)):
```
mgrover3@mgrover3-VirtualBox:~$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyne
>>> import pymoab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pymoab
>>> from pyne import mesh
/home/mgrover3/.local/lib/python2.7/site-packages/pyne/mesh.py:2: QAWarning: pyne.data is not yet QA compliant.
  from pyne.material import Material, MaterialLibrary, MultiMaterial
/home/mgrover3/.local/lib/python2.7/site-packages/pyne/mesh.py:2: QAWarning: pyne.material is not yet QA compliant.
  from pyne.material import Material, MaterialLibrary, MultiMaterial
/home/mgrover3/.local/lib/python2.7/site-packages/pyne/mesh.py:14: QAWarning: pyne.mesh is not yet QA compliant.
  warn(__name__ + " is not yet QA compliant.", QAWarning)
/home/mgrover3/.local/lib/python2.7/site-packages/pyne/mesh.py:26: QAWarning: The PyMOAB optional dependency could not be imported. Some aspects of the mesh module may be incomplete.
  "Some aspects of the mesh module may be incomplete.", QAWarning)
>>> coords = [[0,1,2,3,4],[0,1,2,3],[0,1]]
>>> m = mesh.Mesh(structured=True,structured_coords=coords)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mgrover3/.local/lib/python2.7/site-packages/pyne/mesh.py", line 708, in __init__
    self.mesh = mb_core.Core()
NameError: global name 'mb_core' is not defined
```
What makes sense to me is to no longer install PyTAPS and install a newer release of MOAB that contains the PyMOAB module, but I'm not sure which release to choose.

**Comment by gonuke** [comment]
This is correct! We need to update install scripts for this change.  There is a dockerfile in `pyne/PyNE` that provides guidance, as well as #26 here

**Comment by gonuke** [comment]
P.S. MOAB version 5.1.0 is the best version

**Comment by Mongwell** [comment]
I think MOAB v5.1.0 requires a more recent version of Cython than is obtainable through `apt`. A more recent version is available through `pip`, but if `pip` has to be installed through the script, I think all python dependencies should be installed through `pip` then, to keep the package managers used by python limited to one.

I've made those changes on the `ubuntu_16.04.sh` script and tested it. It seems to work correctly. I'll have to also change the other scripts if this is deemed a good solution.

**Comment by gonuke** [comment]
This seems reasonable - I’m interested in thoughts from @bam241 and @kkiesling on this topic since they were most familiar in the recent months

**Comment by bam241** [comment]
@gonuke I never played to much with this, but I implemented the same solution to build the pyne docker image used in the CI. [[see](https://github.com/pyne/pyne/blob/develop/docker/ubuntu_18.04-dev.dockerfile)] at least for most of the python lib...

**Comment by Mongwell** [comment]
I've changed my fork of the scripts so that running `ubuntu_16.04.sh` will now properly install PyNE (dev or stable) with PyMOAB. I've also created an `ubuntu_18.04.sh` script that does the same. There is a minor complication that I couldn't simplify, where the installer has to restart their shell or source their `.bashrc` manually to obtain update their `PYTHONPATH` environment variable.

I'm not sure if it's possible to update the Ubuntu 14.04, 15.04, and Mint 17.3 scripts to install PyNE with PyMOAB. The versions of the dependencies available to those distributions are too old for PyMOAB. Are they still necessary and worth updating, or can they be removed?

**Comment by gonuke** [comment]
I think the old Ubuntu can definitely be removed.  I'm not sure about Mint since I don't use it... that was originally done for collaborators at KSU such as @RLReed

**Comment by bam241** [comment]
Maybe you could issue a PR draft (when you issue a PR you can use the down arrow to make a draft instead of the full PR, that can be changed later on into a normal PR)  so we can have a better support for the discussion ?

I personnally think that we should NOT support old ubuntu version (LTS is 5y so everything older than 5y should go away...)

**Comment by bam241** [comment]
@Mongwell a `source .bashrc` might fix the `PYTHONPATH` update problem :)

**Comment by Mongwell** [comment]
It will, but it has to be run by the installer in the shell from which they are running the script. The `PYTHONPATH` environment variable has to be created in the shell that `python` will be run from. I tried adding `source ~/.bashrc` to the script, but that won't work because a process can only modify its own environment variables.
I've added that as an instruction in the post-installation printouts. It is also written as an instruction in the comments of the scripts (excluding `ubuntu_mint.sh`).

**Comment by bam241** [comment]
what if you try to source the script instead of running it ?

**Comment by Mongwell** [comment]
It works about the same as running the script, except it closes the terminal emulator after the script finishes, so I'm not sure if it's the best option.

**Comment by gonuke** [comment]
(I'm going to move comments over to the PR comment thread)
