### ISSUE TITLE
Add install script for programs used to build documentation

### ISSUE THREAD

**Issue by nathanb01** [pyne/install_scripts#34]
We currently have build scripts for pyne and yt, it might be useful to include an install script for the programs that are used to build the documentation.

**Comment by gonuke** [comment]
Thanks for bringing this up @nathanb01!  We've recently added some information within the `pyne/pyne` repo for this and decided to not include it in these install scripts.  

Rationale: 
1. Most users who are relying on the `install_scripts` will not be interested in building local copies of the documentation and are more likely to consult the website.  
1. Most users who are building the website will be experienced in building PyNE and living mostly in the `pyne/pyne` repo.
Therefore, we should focus on doc/website building instructions and support in that one place.

Others (esp. @katyhuff ) may have additional thoughts on this, so we welcome feedback on this decision.
