### ISSUE TITLE
dockerfile needed ?

### ISSUE THREAD

**Issue by bam241** [pyne/install_scripts#36]
As we now have 6 different dockerfiles used for the `pyne/pyne` CI (combinations of Python2-3/MOAB/DAGMC) why don't we rely on those, and avoid supporting 4 additional Dockerfiles ?

We could automatically push a stable and a dev version of those docker container on PR merge on `develop` and on tags (as it is done the website PR pyne/pyne#1086)

**Comment by gonuke** [comment]
I think we agreed that stand-alone dockerfiles are instructive and serve a different purpose that the CI dockerfiles, but automatically pushing such files is a good option.

**Comment by bam241** [comment]
Yes! we did agreed... and I forgot about it....
sorry :)

**Comment by bam241** [comment]
closing, moved into the pyne repo pyne/pyne#1161
