### ISSUE TITLE
Ubuntu 18.04 install script

### ISSUE THREAD

**Issue by kyfranzen** [pyne/install_scripts#39]
Running
./ubuntu_18.04.sh stable
stopped with 

Installing collected packages: pip
Successfully installed pip-19.3.1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/d7/b1/3367ea1f372957f97a6752ec725b87886e12af1415216feec9067e31df70/numpy-1.16.5-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
     |████████████████████████████████| 17.0MB 11.4MB/s 
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/1d/f6/7c16d60aeb3694e5611976cb4f1eaf1c6b7f1e7c55771d691013405a02ea/scipy-1.2.2-cp27-cp27mu-manylinux1_x86_64.whl (24.8MB)
     |████████████████████████████████| 24.8MB 23.1MB/s 
Collecting cython
  Downloading https://files.pythonhosted.org/packages/91/00/f5891fa0e95b14bb7f5698fc4da3139318d3e36b12a49c7598936afd4f08/Cython-0.29.13-cp27-cp27mu-manylinux1_x86_64.whl (2.0MB)
     |████████████████████████████████| 2.0MB 5.9MB/s 
Collecting nose
  Downloading https://files.pythonhosted.org/packages/99/4f/13fb671119e65c4dce97c60e67d3fd9e6f7f809f2b307e2611f4701205cb/nose-1.3.7-py2-none-any.whl (154kB)
     |████████████████████████████████| 163kB 9.0MB/s 
Collecting tables
  Downloading https://files.pythonhosted.org/packages/fb/b6/f7128895d328f64e52f61fbb39c03a458f8b583724705bddae392a1085a0/tables-3.6.0.tar.gz (7.8MB)
     |████████████████████████████████| 7.8MB 18.8MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-SsOeQZ/tables/setup.py'"'"'; __file__='"'"'/tmp/pip-install-SsOeQZ/tables/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-SsOeQZ/tables/pip-egg-info
         cwd: /tmp/pip-install-SsOeQZ/tables/
    Complete output (1 lines):
    .. ERROR:: You need Python 3.4 or greater to install PyTables!
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I hope you can help.
Thanks,
Ken

**Comment by gonuke** [comment]
It looks like this requirement for Python 3 is new.  We'll have to investigate a little more, but given the end of life for Python 2.7, it's not a surprise.

**Comment by gonuke** [comment]
In the meantime, you can try changing the `tables` on line 18 of `./ubuntu_18.04.sh` to `tables==3.5.3`.  This should force it to get the last version of PyTables that did support Python 2.7

**Comment by kyfranzen** [comment]
Thanks, I ended up installing Py Tables by manually running
> pip3 install tables==3.5.2
and removing tables from the pic_package_list in the 18.04 install script which seemed to remove this obstacle. However, the script then later on reported an error during the test.

I also tested the r2s.py script which is reporting a missing dagmc module.
 
I will move this discussion to the PyNE Users google group per your request.

Many thanks,
Ken

**Comment by bam241** [comment]
> On Oct 22, 2019, at 16:03, kyfranzen <notifications@github.com> wrote:
> 
> Thanks, I ended up installing Py Tables by manually running
> 
> pip3 install tables==3.5.2
somethign seems off, as pip3 will install package for python3, not python2...

> and removing tables from the pic_package_list in the 18.04 install script which seemed to remove this obstacle. However, the script then later on reported an error during the test.
> 
> I also tested the r2s.py script which is reporting a missing dagmc module.
> 
> I will move this discussion to the PyNE Users google group per your request.
> 
> Many thanks,
> Ken
> 

I am trying the install script with th efix that Paul offered.
I’ll let you know how it went


Baptiste

**Comment by kkiesling** [comment]
closing since we have updated to python 3 as off the latest release and the install scripts have been updated accordingly
