### ISSUE TITLE
Install_script for ubuntu_18.04.sh

### ISSUE THREAD

**Issue by horrorgram** [pyne/install_scripts#40]
Hello,

I tried to install ubuntu_18.04.sh and received the following error message:
ubuntu_18.04.sh: line 7: syntax error near unexpected token `newline'
ubuntu_18.04.sh: line 7: `<!DOCTYPE html>'

I received the same message when running ubuntu_16.04.sh as well. I appreciate any helps on this.

**Comment by gonuke** [comment]
Sorry that you are running into this problem @horrorgram.

Can you tell me more about what kind of system you are using?  I am not seeing this error when I run on a clean Ubuntu 18.04 system, so I can't replicate it.  Perhaps if you provide more information we can figure it out together.

**Comment by horrorgram** [comment]
@gonuke 

I am running a VM through Putty and have Ubuntu 19.10.
Maybe I should try install Ubuntu 18.04 instead and try it again. I will let you know. 

Thank you very much

**Comment by bam241** [comment]
@horrorgram I also notice on a fresh 18.04 an error (not the same as yours tho) when running `bash ubuntu_18.04.sh` without argument.
it worked with `bash ubuntu_18.04.sh dev` (should get you the last version of `develop` branch of PyNE/pyne)
And I think an other option is: `bash ubuntu_18.04.sh stable` with should get you the last release version...

**Comment by horrorgram** [comment]
Yes, that solved the issue.

Thank you everyone

**Comment by bam241** [comment]
@horrorgram 
May I ask which solution fixed your issue ? the using ubuntu 18.04 or the argument ?
