### ISSUE TITLE
refactor install scripts to be more user friendly

### ISSUE THREAD

**Issue by kkiesling** [pyne/install_scripts#57]
One of the goals of this repo is to provide a good starting script for new users to either outright run and use or reference to tweak for their own system. Right now the there are separate files based on the user's OS (good), but they also call a script from a completely separate file. It would probably be more beneficial to maintain entirely separate scripts for each OS that we support rather than break it up into separate files. Benefits of keeping single files are (1) allowing users to only download a single file rather than cloning an entire repo, and (2) keeping a single file for reference without the mental load on new users to jump between multiple files.

**Comment by kkiesling** [comment]
per discussion w/ @bam241 and @gonuke - we may want to add a "philosophy" section to the readme so that we don't go through clever refactoring in the future to make these scripts too complicated for new users.

**Comment by bam241** [comment]
I also think we should remove python3-pip package as package we install. se we remain python version agnostic.

And probably specifying somewhere that both `python` and `pip` package are required. Providing command line to install them...

**Comment by kkiesling** [comment]
> I also think we should remove python3-pip package as package we install. se we remain python version agnostic.

I think we have come to consensus on this issue as we are only supporting python 3 now. And we have refactored. Do you think we can close this now @bam241 ?

**Comment by kkiesling** [comment]
> @kkiesling is that still an issue or was that resolved on the last hack-a-thon ?

considering my comment above on Aug 25, I think that yes, we can close this now
