### ISSUE TITLE
backwards compatibility issue?

### ISSUE THREAD

**Issue by py1sl** [pyne/install_scripts#8]
i tried using this script on a completely clean new ubuntu 14.04 LTS Virtual machine and get the following error:

configure: creating ./config.lt
config.lt: creating libtool
checking ieeefp.h usability... no
checking ieeefp.h presence... no
checking for ieeefp.h... no
checking for C++ unordered_map... std::tr1
checking for mpiexec... no
checking for mpirun... no
checking for deflate in -lz... yes
checking for SZ_Decompress in -lsz... no
checking if HDF5 support is enabled... yes
configure: error: "/usr/lib/x86_64-linux-gnu/hdf5/serial is not a directory."
This is in the moab/configure section

**Comment by elliottbiondo** [comment]
Yes I believe apt puts HDF5 in different places on 14.04 and 15.04. Within the install script you should be able to change:

"/usr/lib/x86_64-linux-gnu/hdf5/serial"

to:

/usr/lib/x86_64-linux-gnu/hdf5/

and everything should work. Note that this path appears in several places. Please let me know if that fixes everything and I will put in a PR for a separate 14.04 script.

**Comment by py1sl** [comment]
Hi Elliot

HDF5 on 14.04 is in :
/usr/lib/x86_64-linux-gnu/
i changed the moab configure line to look at that and it runs almost to completion, but nose tests have several errors with moab, not only test_r2s, but also test_dagmc

Testing test_r2s.py:

Requested faceting tolerance: 0
MOAB ERROR: --------------------- Error Message ------------------------------------
MOAB ERROR: Unrecognized option: ""!
MOAB ERROR: load_file() line 530 in src/Core.cpp
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
MOAB ERROR: get_data() line 121 in src/VarLenSparseTag.cpp
MOAB ERROR: get_data() line 121 in src/VarLenSparseTag.cpp
MOAB ERROR: get_data() line 121 in src/VarLenSparseTag.cpp
..Requested faceting tolerance: 0
MOAB ERROR: --------------------- Error Message ------------------------------------
MOAB ERROR: Unrecognized option: ""!
MOAB ERROR: load_file() line 530 in src/Core.cpp
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
MOAB ERROR: get_data() line 121 in src/VarLenSparseTag.cpp
MOAB ERROR: get_data() line 121 in src/VarLenSparseTag.cpp
MOAB ERROR: get_data() line 121 in src/VarLenSparseTag.cpp
..
----------------------------------------------------------------------
Ran 4 tests in 0.310s

I'll do a PR once its fixed

**Comment by elliottbiondo** [comment]
Actually I think those errors are okay... @makeclean can confirm.

**Comment by makeclean** [comment]
Yeah, they aren't a problem, I thought they were fixed in an earlier version of MOAB than 4.8? Ill look into why these are appearing.

**Comment by py1sl** [comment]
Ok,  there is still one test failure when using nosetests but not when using travis-run-tests.sh and has been reported on the google group.
should the install script be changed to use the travis-run-tests.sh?
if so i'd change it and submit the PR

**Comment by elliottbiondo** [comment]
Yes, that sounds good.
